# Generated by Django 3.2.5 on 2021-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_delited',
            field=models.BooleanField(default=False),
        ),
    ]
